site_name: datatui
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: lime 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <Your Name>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/koaning
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fishnets88
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/vincentwarmerdam

extra_css:
  - stylesheets/css/extra.css

nav:
  - home: index.md
  - cli: cli.md 
  - api: api.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python