name: Code Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install Venv
      run: uv venv
    - name: Install Dependencies
      run: make install
    - name: Test
      run: uv run pytest
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
          name: snapshots
          path: snapshot_report.html
    - name: Ruff
      run: uv run ruff check .
